version: '3.8'
services:
  transcontainer1:
    build: .
    ports:
      - "50000-50002:50000-50002/udp"
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 256M

  examples:
    build:
      context: .
      dockerfile: Dockerfile-examples
    ports:
      - "9999:8080"
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 256M

