// Code generated by interfacer; DO NOT EDIT

package webrtc

type IAPI interface {
        NewDTLSTransport(*ICETransport, []Certificate) (*DTLSTransport, error)
        // NewDataChannel(*SCTPTransport, *DataChannelParameters) (*DataChannel, error)
        NewIDataChannel(*SCTPTransport, *DataChannelParameters) (IDataChannel, error)
        NewICEGatherer(ICEGatherOptions) (*ICEGatherer, error)
        NewICETransport(*ICEGatherer) *ICETransport
        NewIPeerConnection(Configuration) (IPeerConnection, error)
        // NewPeerConnection(Configuration) (*PeerConnection, error)
        NewRTPReceiver(RTPCodecType, *DTLSTransport) (*RTPReceiver, error)
        NewRTPSender(TrackLocal, *DTLSTransport) (*RTPSender, error)
        NewSCTPTransport(*DTLSTransport) *SCTPTransport
}
